name: pfedfda
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.11.5
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.0.0
      - appdirs==1.4.4
      - cachetools==5.3.2
      - calmsize==0.1.3
      - certifi==2023.11.17
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - clarabel==0.6.0
      - click==8.1.7
      - contourpy==1.2.0
      - cvxpy==1.4.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - ecos==2.0.12
      - filelock==3.13.1
      - fonttools==4.47.0
      - fsspec==2023.12.2
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.25.2
      - google-auth-oauthlib==1.2.0
      - grpcio==1.60.0
      - h5py==3.10.0
      - idna==3.6
      - imageio==2.36.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - markdown==3.5.1
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - memory-profiler==0.61.0
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opacus==1.4.0
      - opencv-python==4.10.0.84
      - opt-einsum==3.3.0
      - osqp==0.6.3
      - packaging==23.2
      - pandas==2.1.4
      - patsy==0.5.6
      - pillow==10.1.0
      - portalocker==2.8.2
      - protobuf==4.23.4
      - psutil==5.9.7
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pybind11==2.11.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytorch-minimize==0.0.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - qdldl==0.1.7.post0
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-image==0.24.0
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - scs==3.2.4.post1
      - seaborn==0.13.0
      - sentry-sdk==1.39.1
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - statsmodels==0.14.4
      - sympy==1.12
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.2.0
      - tifffile==2024.9.20
      - torch==2.1.2
      - torchaudio==2.1.2
      - torchvision==0.16.2
      - tqdm==4.66.1
      - triton==2.1.0
      - typing-extensions==4.9.0
      - tzdata==2023.3
      - ujson==5.9.0
      - urllib3==2.1.0
      - wand==0.6.13
      - wandb==0.16.1
      - werkzeug==3.0.1
